spring:

  # Application
  application:
    name: feign-mocking

  # Jackson
  jackson:
    default-property-inclusion: NON_NULL

# Server Configuration
server:
  port: 9600
  error:
    include-message: always
    include-binding-errors: always

# Services
services:
  cat-boy:
    name: "cat-boy"
    url: 127.0.0.1:8100
    ping-url: /ping
    img-url: /img