eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://pc.me:8761/eureka
  instance:
    hostname: pc.me

logging:
  level:
    reactivefeign.client.log: TRACE

reactive:
  feign:
    circuit.breaker:
      enabled: false
    logger:
      enabled: true

server:
  port: 0

spring:
  application:
    name: quote-service